// <auto-generated />
using System;
using ChamberAppel.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ChamberAppel.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240918232402_ReWriteUtilisateurTable")]
    partial class ReWriteUtilisateurTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChamberAppel.Domain.Models.ChamberAppelDisciplineBudgetaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("A_propos_du_CRC_de_la_region")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Appelant")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Centre_comptable")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Conseiller_rapporteur")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Conseiller_rapporteur_successeur")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Convoquer_observateur_et_avocat_pour_assister_a_audience_de_determination_de_la_peine")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Date_a_laquelle_avocat_a_ete_informe")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_a_laquelle_avocat_a_recu_la_convocation_pour_inspection")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_a_laquelle_le_dossier_a_ete_renvoye_par_le_bureau_central_de_contrôle")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_a_laquelle_le_rapport_a_ete_prepare")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_a_laquelle_le_suiveur_a_ete_informe")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_a_laquelle_le_suiveur_a_reçu_la_convocation_pour_inspection")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_audience_du_jugement")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_de_audience_de_determination_de_la_peine")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_de_demande_de_documents_complementaires")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_de_realisation_de_la_recherche_sur_le_terrain")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Date_enregistrement_de_la_requete_aupres_du_CRC")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Date_et_numero_de_arrete_designant_le_rapporteur_successeur")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Date_et_numero_de_la_requete_du_ministere_public")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Date_et_numero_de_ordre_de_nomination_du_conseiller_programme")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Date_et_numero_des_conclusions_du_ministere_public")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Date_et_numero_des_conclusions_du_parquet")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("La_date_a_laquelle_la_decision_a_ete_envoyee_pour_notification_aux_parties")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("La_date_a_laquelle_la_petition_a_ete_envoyee_aux_parties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("La_date_a_laquelle_le_comptable_a_reçu_une_copie_de_la_decision")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("La_date_a_laquelle_le_dossier_a_ete_transmis_au_ministere_public")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("La_date_a_laquelle_observateur_a_ete_convoque_a_audience")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Numero_de_dossier")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Numero_de_resolution")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Numero_de_verdict_appelant")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Operateur_de_decision")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Parties")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Publie_le")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("ChamberAppelDisciplineBudgetaires");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.PersonnePhysique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("NomArabe")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("PrenomArabe")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("Id");

                    b.ToTable("PersonnePhysiques");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.RolePermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<Guid>("PersonnePhysiqueId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnePhysiqueId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.UtilisateurLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.ToTable("UtilisateurLogs");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.UtilisateurPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("UtilisateurPermissions");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.UtilisateurRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("UtilisateurRoles");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.RolePermissions", b =>
                {
                    b.HasOne("ChamberAppel.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamberAppel.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.Utilisateur", b =>
                {
                    b.HasOne("ChamberAppel.Domain.Models.PersonnePhysique", "PersonnePhysique")
                        .WithMany()
                        .HasForeignKey("PersonnePhysiqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonnePhysique");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.UtilisateurPermissions", b =>
                {
                    b.HasOne("ChamberAppel.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamberAppel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ChamberAppel.Domain.Models.UtilisateurRoles", b =>
                {
                    b.HasOne("ChamberAppel.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamberAppel.Domain.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
