<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8" />
		<PackageReference Include="NWebsec.AspNetCore.Mvc" Version="3.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\MyFHSI\Backend\Helpers.Api\Helpers.Api.csproj" />
		<ProjectReference Include="..\ChamberAppel.Application\ChamberAppel.Application.csproj" />
		<ProjectReference Include="..\ChamberAppel.Infrastructure\ChamberAppel.Infrastructure.csproj" />
	</ItemGroup>

</Project>
